<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Flats [
        <!ELEMENT Flats (flat)*>
        <!ELEMENT flat (coordinates|area|numberOfRooms|price|balcony|furnish|house|name)*>
        <!ELEMENT coordinates (x|y)*>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT y (#PCDATA)>
        <!ELEMENT area (#PCDATA)>
        <!ELEMENT numberOfRooms (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT balcony (#PCDATA)>
        <!ELEMENT furnish (#PCDATA)>
        <!ELEMENT house (name|year|numberOfFloors|numberOfFlatsOnFloor|numberOfLifts)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT numberOfFloors (#PCDATA)>
        <!ELEMENT numberOfFlatsOnFloor (#PCDATA)>
        <!ELEMENT numberOfLifts (#PCDATA)>
        ]>
<Flats>
    <flat>
        <name>Curn</name>
        <coordinates>
            <x>3</x>
            <y>4</y>
        </coordinates>
        <area>5.6</area>
        <numberOfRooms>5</numberOfRooms>
        <price>7</price>
        <balcony>true</balcony>
        <furnish>NONE</furnish>
        <house>
            <name>key</name>
            <year>1997</year>
            <numberOfFloors>9</numberOfFloors>
            <numberOfFlatsOnFloor>5</numberOfFlatsOnFloor>
            <numberOfLifts>2</numberOfLifts>
        </house>
    </flat>
    <flat>
        <name>Pork</name>
        <coordinates>
            <x>1</x>
            <y>1</y>
        </coordinates>
        <area>5.6</area>
        <numberOfRooms>5</numberOfRooms>
        <price>6</price>
        <balcony>true</balcony>
        <furnish>NONE</furnish>
        <house>
            <name>key</name>
            <year>1997</year>
            <numberOfFloors>9</numberOfFloors>
            <numberOfFlatsOnFloor>5</numberOfFlatsOnFloor>
            <numberOfLifts>2</numberOfLifts>
        </house>
    </flat>
</Flats>
